import { Locale } from '../locales';
import path from 'path';

export default [
  {
    apifyActorId: 'GQ6U3VrM7r0oh5xG1',
    domains: [
      { domain: 'lovecoupons.co.id', locales: [Locale.id_ID] },
      { domain: 'lovecoupons.no', locales: [Locale.nb_NO] },
      { domain: 'lovecoupons.ae', locales: [Locale.en_AE] },
      { domain: 'lovecoupons.bi', locales: [Locale.fr_BI] },
      { domain: 'lovecoupons.nl', locales: [Locale.nl_NL] },
      { domain: 'lovecoupons.sk', locales: [Locale.sk_SK] },
      { domain: 'lovecoupons.fi', locales: [Locale.fi_FI] },
      { domain: 'lovecoupons.si', locales: [Locale.sl_SI] },
      { domain: 'lovecoupons.ar', locales: [Locale.es_AR] },
      { domain: 'lovecoupons.es', locales: [Locale.es_ES] },
      { domain: 'lovecoupons.mt', locales: [Locale.mt_MT] },
      { domain: 'lovecoupons.com.br', locales: [Locale.pt_BR] },
      { domain: 'lovecoupons.com.sg', locales: [Locale.en_SG] },
      { domain: 'lovecoupons.com.ng', locales: [Locale.en_NG] },
      { domain: 'lovecoupons.lv', locales: [Locale.lv_LV] },
      { domain: 'lovecoupons.com.cm', locales: [Locale.fr_CM] },
      { domain: 'lovecoupons.at', locales: [Locale.de_AT] },
      { domain: 'lovecoupons.fr', locales: [Locale.fr_FR] },
      { domain: 'lovecoupons.pe', locales: [Locale.es_PE] },
      { domain: 'lovecoupons.com', locales: [Locale.en_US] },
      { domain: 'lovecoupons.pl', locales: [Locale.pl_PL] },
      { domain: 'lovecoupons.hk', locales: [Locale.en_HK] },
      { domain: 'lovecoupons.pt', locales: [Locale.pt_PT] },
      { domain: 'lovecoupons.is', locales: [Locale.is_IS] },
      { domain: 'lovecoupons.lt', locales: [Locale.lt_LT] },
      { domain: 'lovecoupons.ma', locales: [Locale.fr_MA] },
      { domain: 'lovecoupons.li', locales: [Locale.de_LI] },
      { domain: 'lovecoupons.co.ke', locales: [Locale.en_KE] },
      { domain: 'lovecoupons.lu', locales: [Locale.fr_LU] },
      { domain: 'lovecoupons.hu', locales: [Locale.hu_HU] },
      { domain: 'lovecoupons.com.hr', locales: [Locale.hr_HR] },
      { domain: 'lovecoupons.ca', locales: [Locale.en_CA] },
      { domain: 'lovecoupons.com.co', locales: [Locale.es_CO] },
      { domain: 'lovecoupons.dk', locales: [Locale.da_DK] },
      { domain: 'lovecoupons.it', locales: [Locale.it_IT] },
      { domain: 'lovecoupons.cz', locales: [Locale.cs_CZ] },
      { domain: 'lovecoupons.com.ua', locales: [Locale.uk_UA] },
      { domain: 'lovecoupons.mx', locales: [Locale.es_MX] },
      { domain: 'lovecoupons.be', locales: [Locale.nl_BE] },
      { domain: 'lovecoupons.se', locales: [Locale.sv_SE] },
      { domain: 'lovecoupons.vn', locales: [Locale.vi_VN] },
      { domain: 'lovecoupons.cl', locales: [Locale.es_CL] },
      { domain: 'lovecoupons.de', locales: [Locale.de_DE] },
      { domain: 'lovecoupons.ro', locales: [Locale.ro_RO] },
      { domain: 'lovecoupons.ee', locales: [Locale.et_EE] },
      { domain: 'lovecoupons.ec', locales: [Locale.es_EC] },
      { domain: 'lovecoupons.rs', locales: [Locale.sr_RS] },
      { domain: 'lovecoupons.com.my', locales: [Locale.en_MY] },
      { domain: 'lovecoupons.tw', locales: [Locale.zh_TW] },
      { domain: 'lovecoupons.co.za', locales: [Locale.en_ZA] },
      { domain: 'lovecoupons.com.ve', locales: [Locale.es_VE] },
      { domain: 'lovecoupons.bg', locales: [Locale.bg_BG] },
      { domain: 'lovecoupons.co.il', locales: [Locale.he_IL] },
      { domain: 'lovecoupons.ch', locales: [Locale.de_CH] },
      { domain: 'lovecoupons.co.in', locales: [Locale.en_IN] },
      { domain: 'lovecoupons.co.nz', locales: [Locale.en_NZ] },
      { domain: 'lovecoupons.com.au', locales: [Locale.en_AU] },
      { domain: 'lovecoupons.uy', locales: [Locale.es_UY] },
      { domain: 'lovecoupons.com.ph', locales: [Locale.en_PH] },
    ],
    name: path.basename(__filename, path.extname(__filename)),
  },
];
