import { Locale } from '../locales';

export default [
  {
    apifyActorId: 'E0ttlQYLdG6AIOQZK',
    domains: [
      {
        domain: 'picodi.com',
        locales: [
          Locale.ru_BY,
          Locale.pt_BR,
          Locale.es_CL,
          Locale.cs_CZ,
          Locale.de_DE,
          Locale.hu_HU,
          Locale.en_IN,
          Locale.id_ID,
          Locale.en_MY,
          Locale.es_MX,
          Locale.en_PH,
          Locale.pl_PL,
          Locale.pt_PT,
          Locale.ro_RO,
          Locale.en_ZA,
          Locale.es_ES,
          Locale.th_TH,
          Locale.tr_TR,
          Locale.uk_UA,
          Locale.en_US,
          Locale.en_AU,
          Locale.de_AT,
          Locale.fr_BE,
          Locale.en_IE,
          Locale.de_CH,
          Locale.en_SG,
          Locale.en_GB,
          Locale.el_GR,
          Locale.en_HK,
          Locale.en_CA,
          Locale.en_SA,
          Locale.en_AE,
          Locale.es_AR,
          Locale.en_NZ,
          Locale.fr_FR,
          Locale.it_IT,
          Locale.en_PK,
          Locale.es_CO,
          Locale.sk_SK,
          Locale.sv_SE,
          Locale.en_NG,
          Locale.fi_FI,
          Locale.es_PE,
        ],
        routes: {
          '/by': Locale.ru_BY,
          '/br': Locale.pt_BR,
          '/cl': Locale.es_CL,
          '/cz': Locale.cs_CZ,
          '/de': Locale.de_DE,
          '/hu': Locale.hu_HU,
          '/in': Locale.en_IN,
          '/id': Locale.id_ID,
          '/my': Locale.en_MY,
          '/mx': Locale.es_MX,
          '/ph': Locale.en_PH,
          '/pl': Locale.pl_PL,
          '/pt': Locale.pt_PT,
          '/ro': Locale.ro_RO,
          '/za': Locale.en_ZA,
          '/es': Locale.es_ES,
          '/th': Locale.th_TH,
          '/tr': Locale.tr_TR,
          '/ua': Locale.uk_UA,
          '/us': Locale.en_US,
          '/au': Locale.en_AU,
          '/at': Locale.de_AT,
          '/be': Locale.fr_BE,
          '/ie': Locale.en_IE,
          '/ch': Locale.de_CH,
          '/sg': Locale.en_SG,
          '/uk': Locale.en_GB,
          '/gr': Locale.el_GR,
          '/hk': Locale.en_HK,
          '/ca': Locale.en_CA,
          '/sa': Locale.en_SA,
          '/ae': Locale.en_AE,
          '/ar': Locale.es_AR,
          '/nz': Locale.en_NZ,
          '/fr': Locale.fr_FR,
          '/it': Locale.it_IT,
          '/pk': Locale.en_PK,
          '/co': Locale.es_CO,
          '/sk': Locale.sk_SK,
          '/se': Locale.sv_SE,
          '/ng': Locale.en_NG,
          '/fi': Locale.fi_FI,
          '/pe': Locale.es_PE,
        },
      },
    ],
    name: 'picodi-com',
  },
];
