import { Locale } from '../locales';

export default [
  {
    apifyActorId: 'E0ttlQYLdG6AIOQZK',
    domains: [
      {
        domain: 'picodi.com',
        locales: [
          Locale.ru_BY,
          Locale.pt_BR,
          Locale.es_CL,
          Locale.cs_CZ,
          Locale.de_DE,
          Locale.hu_HU,
          Locale.en_IN,
          Locale.id_ID,
          Locale.en_MY,
          Locale.es_MX,
          Locale.en_PH,
          Locale.pl_PL,
          Locale.pt_PT,
          Locale.ro_RO,
          Locale.en_ZA,
          Locale.es_ES,
          Locale.th_TH,
          Locale.tr_TR,
          Locale.uk_UA,
          Locale.en_US,
        ],
        routes: {
          '/by': Locale.ru_BY,
          '/br': Locale.pt_BR,
          '/cl': Locale.es_CL,
          '/cz': Locale.cs_CZ,
          '/de': Locale.de_DE,
          '/hu': Locale.hu_HU,
          '/in': Locale.en_IN,
          '/id': Locale.id_ID,
          '/my': Locale.en_MY,
          '/mx': Locale.es_MX,
          '/ph': Locale.en_PH,
          '/pl': Locale.pl_PL,
          '/pt': Locale.pt_PT,
          '/ro': Locale.ro_RO,
          '/za': Locale.en_ZA,
          '/es': Locale.es_ES,
          '/th': Locale.th_TH,
          '/tr': Locale.tr_TR,
          '/ua': Locale.uk_UA,
          '/us': Locale.en_US,
        },
      },
    ],
    name: 'picodi-com',
  },
];
