alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: DATABASE_URL
  scope: RUN_TIME
  type: SECRET
  value: EV[1:+j4Iq3xA1PNTkyArTqnhqSPRxotxJ22c:4Ew2jZx9he0lNlFcEhhTbmWVyHytC93yIr7df4XLWw23hMn0ZmN8ooMjzdjyW0sMGxqdF/hQ+/OcZOzwhatjgPQHoYBNw8A4zCYZ9RPe/YcvbUcOfaYZJV6tQzW8DwFZxecIBWg2nAy7o59ytDPpFWIeDi8hAujCnUOB3UinviJEBVROtfohldm+sjFDL5RZdYse]
- key: DATABASE_URL_NON_POOLED
  scope: RUN_TIME
  type: SECRET
  value: EV[1:blP6VPeahVcseTxQROFnWvoy9J0oseJY:iYuXwzatEM4Btn8eZfNMWgr9iwD8R0cRPwCEov3k9SbJHF0m6y/KJILThVX/yM22dPOLoZHLlSq78/T8nx7rJeEFyWNqOIjpjsl6q5CtOfoLDHRLqyMp0P+q/Jxoq0SlN+pAgN9PF7eR9J/JLdJj7xU8m9azAMX7dwvWGska67NZrQXXRlNwyccC/jcbuQ==]
- key: DATABASE_BACKUP_URL
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:1d8nsEIx0dwasj9G0HKsIs3/f6cw2bF6:AO7mQMXDhcfcLdfiopKfcXzq+Ac9t8HbJ+FewrDhFdYmarkWi+SeTlxmHEXHO8TkEweTGCQQygYQVA8DvdPIu+v5LutSIQdZYyaUxWLmBuKvHiUiJc4eP8px4bChBGOhVg9IAacWHzRVQmLOc6c5MNvIge49v6uUfmJXi6ErN1dOda7kmN2VRWGtQW0MNT7NxKtZw+PNWrxFsGAF]
- key: REDIS_URL
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Vka/hj/QBOi/7VP8YL+gofLmxk3VmJZm:YPsjJPL59Fqp8z8ahbxAtIdDRWvoFpVXMfUrbvrAHIzReOjEmUwUicY4+zdH1wQcEfHsL+L+p93fbLCWV/beXBaPYIIwl+T1fHF5qbUfi8w17I1H00SaYuWKqIufQxjmgHs4+uihpXozDQmlygbIcjoIT74Q9sv/lQ==]
- key: API_SECRET
  scope: RUN_TIME
  type: SECRET
  value: EV[1:kXgU9bORSJixzgzNBUuJZa0lwoMuRJnp:QjhQyyQR/uibHfyyNgFdPZKbQRfxg5R3/vN4wPInCJrdZA==]
- key: API_DOCS_PASSWORD
  scope: RUN_TIME
  type: SECRET
  value: EV[1:03+I38KB3LZqfluX/adrci8uxZohhvvu:/FzuwD/9vVUlmj4uOWIZTJ6NkEC17zGj2KIesLIli748VQ==]
- key: BASE_URL
  scope: RUN_AND_BUILD_TIME
  value: ${_self.PUBLIC_URL}
- key: SENTRY_DSN
  scope: RUN_AND_BUILD_TIME
  value: https://96c2678699afa4564f61777d164df321@o135355.ingest.us.sentry.io/4507737800704000
- key: SENTRY_DSN_ACTORS
  scope: RUN_AND_BUILD_TIME
  value: https://d316ec40331883edb34e4caef3e68a05@o135355.ingest.us.sentry.io/4506838132654080
- key: SENTRY_LOGGING
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: APITALLY_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:gnOWb5nnQIxQZr15jrc45CrTcyNL6GF1:8TVKvzYYpeB8iFdrvJ9Tlg44wWKZYriaH5l2s0WK4QUvXSyAh5VdpwBz2x05FXZMRF6d3A==]
- key: API_RATE_LIMIT
  scope: RUN_AND_BUILD_TIME
  value: "100"
- key: API_COOL_DOWN_TIME
  scope: RUN_AND_BUILD_TIME
  value: "60000"
- key: MAX_CONCURRENT_RUNS
  scope: RUN_AND_BUILD_TIME
  value: "30"
- key: OBERST_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Pcj6p4UKKUMGSpBLaRxbtuuyjAW4xG4W:nVDapKYINQW89TtRBJEE64tOsg2PAK/U2YLpL1PZCpIto7hboZ4TNXoJHOt7mq80lFICpNOYjB4=]
- key: APIFY_ORG_TOKEN_OBERST
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:LOpy3KURbA03wbBezJQmlUjYxvnG8r81:s6gkY5ZHmYSgIkqcwBKKKnFFcMjqAHuSMjpG43zXU0n6+l06bkvU1lhYOOfPxXnYcGKFMWiUFb2BjrEtWcg=]
- key: APIFY_ORG_TOKEN_LEXIS
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:9ikseCjr7Dd6OtGJqsqeyLMR5hoVwznh:KALXt3Fkqwl/wIhs0a84f+wVnSyXJVtk0d6Ocqspcilj3NUQ0iKUVha0ziCYauvgLI1bNjJOes1BCBWYpck=]
- key: APIFY_DAILY_COST_LIMIT_USD
  scope: RUN_AND_BUILD_TIME
  value: "50"
- key: SMTP_HOST
  scope: RUN_AND_BUILD_TIME
- key: SMTP_PORT
  scope: RUN_AND_BUILD_TIME
- key: SMTP_USER
  scope: RUN_AND_BUILD_TIME
- key: SMTP_PASS
  scope: RUN_AND_BUILD_TIME
- key: EMAIL_TO
  scope: RUN_AND_BUILD_TIME
- key: EMAIL_FROM
  scope: RUN_AND_BUILD_TIME
- key: ENABLE_EMAILS
  scope: RUN_AND_BUILD_TIME
  value: "false"
- key: NODE_ENV
  scope: RUN_AND_BUILD_TIME
  value: production
- key: PORT
  scope: RUN_AND_BUILD_TIME
  value: "8080"
- key: TLS_CA_CERT_MONGO
  scope: RUN_AND_BUILD_TIME
  value: |
    -----BEGIN CERTIFICATE-----
    MIIEQTCCAqmgAwIBAgIUDCevkfQZ3xTrjPzhO+G+bcMDmW4wDQYJKoZIhvcNAQEM
    BQAwOjE4MDYGA1UEAwwvMjA1OWZkOGEtZGU4NS00MTVhLTlmNTktOTVkMDRiZTMy
    NmJjIFByb2plY3QgQ0EwHhcNMjMxMjAxMTM0MzUxWhcNMzMxMTI4MTM0MzUxWjA6
    MTgwNgYDVQQDDC8yMDU5ZmQ4YS1kZTg1LTQxNWEtOWY1OS05NWQwNGJlMzI2YmMg
    UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAKVERR7k
    Hqg9iTuWeOvHAuEbYDQh+gqUak8N7u/mApudtHlZQsL0tlSWTIpayVzBcn0TEPlL
    0LOC4jTrGdP77HwwiCCug0zVowbM3rXQdSIv8fwh6zbElGBMoy/CIiP2tx3agOyu
    MVn4nmot/Bndc/kNo2shysTRe0Jpy0j/2b9bK21h45a8PVet7H0uft9i4FxZaxUU
    8/Y3PP0ClSHxpsOWOSgNqCakoFUcHiDQV/KR3OHYoTfoyRt7P1bqqQTjLxro/Prv
    U64hOt/KoxO+CzCTqbyop5rDKeI87JSN04IKLKhi+B7OEoevr/r0EnvNJ170sEvt
    AjamO45ypVh47/+n7TYyLgOTLg/d8Q6GsXMBvfAQQTefzYINYU9tdN1LvYcIAsTc
    8k3D0eE80+M2v0Cusi0OPSZgH761f5rs96CuBVz/tfBignImDxF5Yef+Kdu5KidH
    u6YIwMf5VjS55gMp91tPN6qLa2bQkK3Kz7HGPTSEQQyHAuSZrZtNt8zuXwIDAQAB
    oz8wPTAdBgNVHQ4EFgQUnoClMaU6ADmZdPQKHgEDPPGb0/0wDwYDVR0TBAgwBgEB
    /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAHTv2BZlfrbyn0N9
    5Ujvg0I9ntzKJsuPB4UzGT7iD6u6laTnAmTmne8FuR+8RUWO6Z/SSw/mpHPLvtXN
    wBYn74cPs+AVwBX4OewpwjzS8KJe9hJQyRfDUuRM0e9QemERyQBRdx3qJGGekETB
    9IyaMugDYraDhWM1j7onD8D2ugp8R5H5Q5Gp2ohhrrkVBbVHkJ5qv4QAdnY7FrZ0
    msmQaDfUlmfb6Dtoaz37uxRICx19NWQA49/Ka2lQq9WstUg+KrRRaFkfTRg7P1Nf
    lxyBHSscU65jZoilQT+NqVwK5Z9RmlSKOZeXsv+D3O19vFAPrLuVXIXehumhYhns
    MDoycMk534GWwI+m53ibrQncBpg/RerxOa3jB4DJwaRi3Jw5nhsDMRltzwgRcYHC
    PJgd0rrJYfbq0tX9Ny7wJM+cNU7TxYP7WALucJghId4gJ3gJ366fwthHwIfiWASA
    anvHyyL5LoytN1jIg0NMMLWykErt09pROkqeMHznFd3CmMigoQ==
    -----END CERTIFICATE-----
ingress:
  rules:
  - component:
      name: pipeline
      preserve_path_prefix: true
    match:
      path:
        prefix: /webhooks
  - component:
      name: pipeline
      preserve_path_prefix: true
    match:
      path:
        prefix: /targets
  - component:
      name: pipeline
      preserve_path_prefix: true
    match:
      path:
        prefix: /sentry
  - component:
      name: pipeline
      preserve_path_prefix: true
    match:
      path:
        prefix: /tests
  - component:
      name: api
      preserve_path_prefix: true
    match:
      path:
        prefix: /items
  - component:
      name: api
      preserve_path_prefix: true
    match:
      path:
        prefix: /overview
  - component:
      name: api
      preserve_path_prefix: true
    match:
      path:
        prefix: /exports
  - component:
      name: api
      preserve_path_prefix: true
    match:
      path:
        prefix: /api-docs
  - component:
      name: api
      preserve_path_prefix: true
    match:
      path:
        prefix: /dashboards
name: apify-scrapers
region: fra
services:
- dockerfile_path: docker/Dockerfile.pipeline
  github:
    branch: 584-stage-1
    deploy_on_push: true
    repo: amin-lexis-solutions/apify-scrapers
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-2vcpu-2gb
  name: pipeline
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 60
  autoscaling:
    min_instance_count: 1
    max_instance_count: 3
    metrics:
      cpu:
        percent: 80
- dockerfile_path: docker/Dockerfile.api
  github:
    branch: 584-stage-1
    deploy_on_push: true
    repo: amin-lexis-solutions/apify-scrapers
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-2vcpu-2gb
  name: api
  health_check:
    http_path: /api/
    initial_delay_seconds: 30
    period_seconds: 60
  autoscaling:
    min_instance_count: 1
    max_instance_count: 3
    metrics:
      cpu:
        percent: 80
