FROM node:22.7.0-bullseye

RUN apt-get update

WORKDIR /app

COPY package.prod.json ./package.json
COPY yarn.lock ./
COPY packages/api/package.json ./packages/api/

RUN yarn --silent

COPY packages/api ./packages/api/
COPY packages/shared ./packages/shared/

WORKDIR /app/packages/api

RUN yarn prisma:generate

RUN yarn build

RUN echo "$TLS_CA_CERT_MONGO" >ca-mongo.crt

CMD ["bash", "start.sh"]
