FROM node:22.7.0-bullseye

RUN apt-get update && apt-get -y install cron

WORKDIR /app

COPY package.prod.json ./package.json
COPY yarn.lock ./
COPY packages/api/package.json ./packages/api/

RUN yarn --silent

COPY packages/api ./packages/api/
COPY packages/shared ./packages/shared/

WORKDIR /app/packages/api

# Generate Prisma client
RUN yarn prisma:generate

# Build TypeScript
RUN yarn build

# Create directory for logs
RUN mkdir -p /var/log/pipeline

CMD ["bash", "start-pipeline.sh"]
