name: Ensure Actors Are Shared

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '!packages/api/**'

jobs:
  check-actors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run script that verifies all actors are shared
        env:
          APIFY_ORG_TOKEN_LEXIS: ${{ secrets.APIFY_ORG_TOKEN_LEXIS }}
        run: chmod +x ./scripts/verify-actor-packages-are-owned-by-lexis.sh && ./scripts/verify-actor-packages-are-owned-by-lexis.sh
