name: Deploy Apify Actors

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '!packages/api/**'

  workflow_dispatch:

jobs:
  deploy-actors:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetches the last two commits for comparison

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --prefer-offline --no-optional
        env:
          HUSKY: 0

      - name: Deploy Modified Packages
        uses: ./.github/actions/deploy-actors
        with:
          max_concurrent_runs: 5
          api-token: ${{ secrets.APIFY_ORG_TOKEN_LEXIS }}
          base-url: ${{ secrets.BASE_URL }}
          api-secret: ${{ secrets.API_SECRET }}

  check-shared-actors:
    needs: deploy-actors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: cd ./packages/api && pnpm install
        env:
          HUSKY: 0

      - name: Deploy Shared Actors
        env:
          APIFY_ORG_TOKEN_OBERST: ${{ secrets.APIFY_ORG_TOKEN_OBERST }}
        run: cd ./packages/api && pnpm run scripts:verify-runnable-actors-are-shared-with-oberst