name: Publish wiki
on:
  push:
    branches: [main]
    paths:
      - 'packages/api/wiki/**'
      - 'packages/api/config/**'
  workflow_dispatch:
concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  generate-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: cd packages/api && pnpm install
      - name: Generate wiki
        run: cd packages/api && pnpm run scripts:generate-wiki
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: ./packages/api/wiki