name: Conditional Apify Actor Deployment

on:
  push:
    paths:
      - 'packages/**'

jobs:

  deploy-actors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install
      - name: Install Apify CLI
        run: npm install -g apify-cli
      - name: Authenticate with Apify using API token
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: apify login --token $APIFY_TOKEN
      - name: Deploy actors based on changes
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: |
          changed_dirs=$(git diff --name-only HEAD^ HEAD | grep '/' | cut -d'/' -f1 | sort -u)
          echo "Changed directories: $changed_dirs"
          for dir in $changed_dirs; do
            ACTOR_NAME=$(basename "$dir")
            MAIN_TS="$dir/src/main.ts"
            if [ -f "$MAIN_TS" ]; then
              TYPE="puppeteer" # Default type
              if grep -q "prepareCheerioScraper" "$MAIN_TS"; then
                TYPE="cheerio"
              fi
              echo "Deploying $ACTOR_NAME with $TYPE"
              ./scripts/deploy-apify.js "$ACTOR_NAME" "$TYPE"
            fi
          done
        shell: bash
