name: Simple Apify Actor Deployment

on:
  push:
    paths:
      - 'packages/**'
      - 'scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Updated to use Node.js version 16

      - name: Install dependencies
        run: yarn install

      - name: Check for changes in specific directories
        id: changes
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^packages/|^scripts/' || true)
          if [ -n "$CHANGED" ]; then
            echo "Changes detected in packages or scripts directories."
            echo "::set-output name=triggered::true"
          else
            echo "No changes detected in monitored directories."
            echo "::set-output name=triggered::false"
          fi

      - name: Deploy if changes detected
        if: steps.changes.outputs.triggered == 'true'
        run: |
          echo "Deploying changes..."
          # Replace the following line with your actual deployment command
          ./scripts/deploy-apify.js
