name: Conditional Apify Actor Deployment

on:
  push:
    paths:
      - 'packages/**'
      - 'scripts/**'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Get list of changed files
        id: get_changed_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Process changes and set matrix
        run: node ./scripts/process-changes.js '${{ steps.get_changed_files.outputs.files }}'
        env:
          GITHUB_ENV: ${{ env.GITHUB_ENV }}

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Deploy Actors Based on Matrix
        run: |
          if [[ "${{ env.ACTOR_MATRIX }}" == "all" ]]; then
            # Deploy all actors, adjust the command to your needs
            echo "Deploying all actors..."
            # Example: ./scripts/deploy-all-actors.sh
          else
            IFS=',' read -ra ADDR <<< "${{ env.ACTOR_MATRIX }}"
            for actor in "${ADDR[@]}"; do
              echo "Deploying actor: $actor"
              ./scripts/deploy-apify.js "$actor" puppeteer
            done
          fi
        env:
          ACTOR_MATRIX: ${{ env.ACTOR_MATRIX }}
