name: Rebuild Apify Actor

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'package/**'
      - '!package/api/**'
      - '!package/shared/**'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Apify CLI
        run: npm install -g apify-cli

      - name: Authenticate with Apify using API token
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: apify login --token $APIFY_TOKEN

      - name: Deploy Apify Actor
        run: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
