name: Conditional Apify Actor Deployment

on:
  push:
    paths:
      - 'packages/**'
      - 'scripts/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      rebuild-all: ${{ steps.check-shared.outputs.rebuild-all }}
    steps:
      - uses: actions/checkout@v3

      - name: Check if shared directory has changes
        id: check-shared
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'packages/shared'; then
            echo "::set-output name=rebuild-all::true"
          else
            echo "::set-output name=rebuild-all::false"
          fi

  deploy-actors:
    needs: check-changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Install Apify CLI
        run: npm install -g apify-cli

      - name: Determine actor type and deploy
        run: |
          REBUILD_ALL="${{ needs.check-changes.outputs.rebuild-all }}"
          for dir in packages/*; do
            if [[ -d "$dir" && "$dir" != "packages/api" && "$dir" != "packages/shared" ]]; then
              ACTOR_NAME=$(basename "$dir")
              MAIN_TS="$dir/src/main.ts"
              if [ "$REBUILD_ALL" == "true" ] || [ -f "$MAIN_TS" ]; then
                TYPE="puppeteer" # Default to Puppeteer
                if grep -q "prepareCheerioScraper" "$MAIN_TS"; then
                  TYPE="cheerio"
                fi
                echo "Deploying $ACTOR_NAME with $TYPE"
                ./scripts/deploy-apify.js "$ACTOR_NAME" "$TYPE"
              else
                echo "$MAIN_TS does not exist, skipping $ACTOR_NAME"
              fi
            fi
          done
        shell: bash
